config/urls.py
from django.contrib import admin
from django.urls import path, include
from notes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('notes/', include('notes.urls')),
    path('tasks/', include('tasks.urls')),
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'notes'

urlpatterns = [
    path('list/', views.note_list, name='list'),
    path('create/', views.create_note, name='create'),
    path('detail/<int:notes_id>', views.note_detail, name='detail'),
    path('update/<int:notes_id>', views.note_update, name='update'),
    path('delete/<int:notes_id>', views.note_delete, name='delete'),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('list/', views.task_list, name='list'),
    path('create/', views.create_task, name='create'),
    path('detail/<int:task_id>', views.task_detail, name='detail'),
    path('update/<int:task_id>', views.task_update, name='update'),
    path('delete/<int:task_id>', views.task_delete, name='delete'),
]

notes/models.py
from django.db import models
from django.shortcuts import reverse


class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)


    def get_detail_url(self):
        return reverse('notes:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('notes:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('notes:update', args=[self.pk])

tasks/models.py
from django.db import models
from django.shortcuts import reverse


class Task(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()
    description = models.TextField()


    def get_detail_url(self):
        return reverse('tasks:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('tasks:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('tasks:update', args=[self.pk])

notes/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Note


def home(request):
    return render(request,'index.html')


def note_list(request):
    notes = Note.objects.all()
    ctx = {'notes':notes}
    return render(request, 'notes/note-list.html', ctx)


def create_note(request):
    if request.method == 'POST':
        title=request.POST.get('title')
        content=request.POST.get('content')
        if title and content:
            Note.objects.create(
                title = title,
                content = content
            )
            return redirect('notes:list')
    return render(request, 'notes/note-create.html')


def note_detail(request, notes_id):
    notes = get_object_or_404(Note, pk=notes_id)
    ctx = {'notes':notes}
    return render(request, 'notes/note-detail.html', ctx)


def note_update(request, notes_id):
    notes = get_object_or_404(Note, pk=notes_id)
    if request.method == 'POST':
        title=request.POST.get('title')
        content=request.POST.get('content')
        if title and content:
            notes.title = title
            notes.content = content
            notes.save()
            return redirect(notes.get_detail_url())
    ctx = {'notes':notes}
    return render(request, 'notes/note-create.html', ctx)


def note_delete(request, notes_id):
    notes = get_object_or_404(Note, pk=notes_id)
    notes.delete()
    return redirect('notes:list')

tasks/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Task


def home(request):
    return render(request,'index.html')


def task_list(request):
    tasks = Task.objects.all()
    ctx = {'tasks':tasks}
    return render(request, 'tasks/task-list.html', ctx)


def create_task(request):
    if request.method == 'POST':
        title=request.POST.get('title')
        due_date=request.POST.get('due_date')
        description=request.POST.get('description')
        if title and due_date and description:
            Task.objects.create(
                title = title,
                due_date = due_date,
                description = description
            )
            return redirect('tasks:list')
    return render(request, 'tasks/task-create.html')


def task_detail(request, task_id):
    tasks = get_object_or_404(Task, pk=task_id)
    ctx = {'tasks':tasks}
    return render(request, 'tasks/task-detail.html', ctx)


def task_update(request, task_id):
    tasks = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        title=request.POST.get('title')
        due_date=request.POST.get('due_date')
        description=request.POST.get('description')
        if title and due_date and description:
            tasks.title = title
            tasks.due_date = due_date
            tasks.description = description
            tasks.save()
            return redirect(tasks.get_detail_url())
    ctx = {'tasks':tasks}
    return render(request, 'tasks/task-create.html', ctx)


def task_delete(request, task_id):
    tasks = get_object_or_404(Task, pk=task_id)
    tasks.delete()
    return redirect('tasks:list')

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Home Page</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>Welcome to the Home Page</h1>
    <a href="{% url 'notes:list' %}" class="list-btn">Go to Note List</a><br><br>
    <a href="{% url 'tasks:list' %}" class="list-btn">Go to Tasks List</a>
</body>
</html>

templates/notes/note-create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if notes %}Update Note {% else %}Create Note{% endif %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>{% if notes %}Update Note {% else %}Create Note{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="note-form">
            <label for="title">Note Title:</label><br>
            <input id="title" type="text" name="title" value="{{ notes.title }}"><br><br>
            <label for="content">Note Content:</label><br>
            <textarea id="content" name="content" value="{{ notes.content }}"></textarea><br><br>
        </div>
        <button type="submit" class="update-btn">{% if notes %}Update{% else %}Create{% endif %}</button>
    </form>
    <br>
    {% if notes %}
        <a href="{{ notes.get_detail_url }}" class="back-btn">Back to Detail</a>
    {% else %}
        <a href="{% url 'notes:list' %}" class="back-btn">Back to List</a>
    {% endif %}
</body>
</html>

templates/notes/note-detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ notes.title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <button class="update-btn"><a href="{{ notes.get_update_url }}">Update</a></button>
    <h1>Note Detail</h1>
    <div class="note-detail">
        <h2>Note: {{ notes.title }}</h2>
        <h3>Content: {{ notes.content }}</h3>
    </div>
    <a href="{% url 'notes:list' %}" class="back-btn">Back to Note List</a>
    <button class="delete-btn"><a href="{{ notes.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/notes/note-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Note List</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <h1>Note List</h1>
  <a href="{% url 'notes:create' %}" class="create-btn">Create Note</a><br><br>
  {% for note in notes %}
    <a href="{{ note.get_detail_url }}" class="note-link">Note {{ note.id }}: {{ note.title }}</a><br>
  {% empty %}
    <h3>No Notes</h3>
  {% endfor %}
    <a href="{% url 'home' %}" class="back-btn">Back to Home</a>
</body>
</html>

templates/tasks/task-create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if tasks %}Update Task {% else %}Create Task{% endif %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1 class="task-h1">{% if tasks %}Update Task {% else %}Create Task{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        <label for="title">Task Title:</label><br>
        <input id="title" type="text" name="title" value="{{ tasks.title }}"><br><br>
        <label for="due_date">Due Date:</label><br>
        <input id="due_date" name="due_date" type="date" value="{{ tasks.due_date }}"><br><br>
        <label for="description">Description:</label><br>
        <textarea id="description" name="description" value="{{ tasks.description }}"></textarea><br><br>
        <button type="submit" class="update-task">{% if tasks %}Update Task{% else %}Create Task{% endif %}</button>
    </form>
    <br>
    {% if tasks %}
        <a href="{{ tasks.get_detail_url }}" class="back-btn">Back to Task Detail</a>
    {% else %}
        <a href="{% url 'tasks:list' %}" class="back-btn">Back to Task List</a>
    {% endif %}
</body>
</html>

templates/tasks/task-detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tasks.title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <button class="update-task"><a href="{{ tasks.get_update_url }}">Update Task</a></button>
    <h1 class="task-h1">Task Detail</h1>
    <div class="task-detail">
        <h2>Task: {{ tasks.title | upper }}</h2>
        <h3>Due Date: {{ tasks.due_date | date:"Y-m-d" }}</h3>
        <h3>Description: {{ tasks.description }}</h3>
    </div>
    <a href="{% url 'tasks:list' %}" class="back-btn">Back to Task List</a>
    <button class="delete-btn"><a href="{{ tasks.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/tasks/task-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task List</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <h1 class="task-h1">Task List</h1>
  <a href="{% url 'tasks:create' %}" class="create-task">Create Task</a><br><br>
  {% for task in tasks %}
    <a href="{{ task.get_detail_url }}" class="list-btn">{{ task.title }}</a>
  {% empty %}
    <h3>No Tasks</h3>
  {% endfor %}
  <br><br>
  <a href="{% url 'home' %}" class="back-btn">Back to Home</a>
</body>
</html>